services:
  sne:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6440:5432"
    volumes:
      - ./data:/whpgdata
    environment:
      - container=docker
    platform: linux/amd64
    hostname: whpgdb-primary
